export const USER_API_END_POINT = process.env.REACT_APP_USER_API_END_POINT;
export const JOB_API_END_POINT = process.env.REACT_APP_JOB_API_END_POINT;
export const APPLICATION_API_END_POINT = process.env.REACT_APP_APPLICATION_API_END_POINT;
export const COMPANY_API_END_POINT = process.env.REACT_APP_COMPANY_API_END_POINT;
